# Generated by Django 4.2.1 on 2023-06-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_image", models.ImageField(upload_to="photos/login")),
                ("signup", models.ImageField(upload_to="photos/signup")),
                ("background image", models.ImageField(upload_to="photos/background")),
            ],
        ),
    ]
