# Generated by Django 4.2.1 on 2023-06-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_image", models.ImageField(upload_to="photos/login")),
                ("signup", models.ImageField(upload_to="photos/signup")),
                ("background image", models.ImageField(upload_to="photos/background")),
            ],
        ),
        migrations.DeleteModel(
            name="Images",
        ),
    ]
