# Generated by Django 4.2.1 on 2023-06-19 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_image_delete_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="background image",
            new_name="background_image",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="signup",
            new_name="signup_image",
        ),
    ]
