# Generated by Django 4.2.1 on 2023-05-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
        ('games', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='games', on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
