# Generated by Django 4.2.1 on 2023-06-19 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_carousel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carousel",
            old_name="image",
            new_name="images",
        ),
    ]
